baseURL = 'https://colinjoc.github.io/'
languageCode = 'en-us'
title = 'Col — AI Research & Engineering'

[params]
  description = 'Hypothesis-Driven Research across science and engineering'

buildFuture = true

[markup.goldmark.renderer]
  unsafe = true
